services:
  jupyter:
    image: OEC-Lab1/jupyter:1.0
    container_name: 'OEC-Lab1-jupyter'
    environment:
      - TZ= Asia/Tokyo
    build: ./jupyter
    working_dir: '/home/jovyan/work'
    volumes:
      - ../jupyter:/home/jovyan/work
    stdin_open: true
    tty: true
